name: example
description: RAWG Api example app

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  bloc_pattern: ^2.3.0
  cached_network_image: ^2.1.0+1
  lovelydialogs: ^0.0.2
  rawg_api: 
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true